# Generated by Django 5.2 on 2025-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_farmer_options_product_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='fio',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
